services:

  postgres:
    image: postgres:15
    container_name: postgres-sql-modern-fne
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modern_hygiene_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - modern-hygiene-fne-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d modern_hygiene_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  springboot:
    image: astairenazaire/modern-backend:1.0
    container_name: springboot-modern-hygiene-fne
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/modern_hygiene_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8089
    ports:
      - "8089:8089"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - modern-hygiene-fne-network
    restart: unless-stopped

  frontend:
    image: astairenazaire/modern-frontend:1.0
    container_name: angular-modern-hygiene-fne
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
      - modern-hygiene-fne-network
    restart: unless-stopped

networks:
  modern-hygiene-fne-network:
    driver: bridge

volumes:
  postgres:
    driver: local
