# spring:
#   datasource:
#     url: jdbc:postgresql://postgres:5432/tata_fne_db
#     username: username
#     password: password
#     driver-class-name: org.postgresql.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#     database: postgresql
#     database-platform: org.hibernate.dialect.PostgreSQLDialect

#   mail:
#     host: mail-dev
#     port: 1025
#     username: michel
#     password: michel
#     properties:
#       mail:
#         smtp:
#           trust: "*"
#         auth: false
#         starttls:
#           enabled: false

# server:
#   port: 8089

# application:
#   security:
#     jwt:
#       secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#       expiration: 86400000
#       refresh-token:
#         expiration: 604800000

#   mailing:
#     frontend:
#       activation-url: http://57.129.119.224/activate-account

#   file:
#     uploads:
#       photos-output-path: ./uploads

# fne:
#   base-url: http://54.247.95.108/ws
#   sign-path: /external/invoices/sign
#   bearer-token: NZrZKVylaPzf2APARYi6bEYn40oXCNqE

# invoice:
#   api:
#     base-url: http://54.247.95.108
#     sign-path: /ws/external/invoices/sign
#     token: NZrZKVylaPzf2APARYi6bEYn40oXCNqE
###########################################################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tata_fne_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: michel
    password: michel
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8089

fne:
  base-url: http://54.247.95.108/ws
  sign-path: /external/invoices/sign
  bearer-token: NZrZKVylaPzf2APARYi6bEYn40oXCNqE

invoice:
  api:
    base-url: http://54.247.95.108
    sign-path: /ws/external/invoices/sign
    
    token: NZrZKVylaPzf2APARYi6bEYn40oXCNqE